### ISSUE TITLE
Default socket / passwordless based connection

### ISSUE THREAD

**Issue by SamSaffron** [deepfryed/swift-db-postgres#3]
One thing that bugged me a bit about my bench was

https://github.com/discourse/mini_sql/blob/1264db6ba31d438cb10f1be450ccdcae22c74dc1/bench/timestamp_perf.rb#L148-L148

I tried connecting without that but I got:

```
timestamp_perf.rb:148:in `initialize': fe_sendauth: no password supplied (Swift::ConnectionError)
```

So I am guessing it either should be bypassing fe_sendauth here or is not using the socket by default like pg gem likes to.

**Comment by deepfryed** [comment]
fixed in 8f38f37785345d819ceea2be69fcac8f83bcbe3d
