### ISSUE TITLE
Getting values without the Hash

### ISSUE THREAD

**Issue by SamSaffron** [deepfryed/swift-db-postgres#4]
I was wondering if we could add a `.getvalue(row, col)` method to Result?

https://github.com/deepfryed/swift-db-postgres/blob/master/ext/swift/db/postgres/result.c#L99-L115

This would allow me to directly grab and map the results to objects without an intermediary Hash.

**Comment by deepfryed** [comment]
added in 90d81ff1641bb89fb608eee0f999a1b77eb46638

`Swift::DB::Postgres::Result#get(row, column)`
